nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.1.0.cjs

compressionLevel: mixed

enableGlobalCache: false

supportedArchitectures: 
  os:
    - 'darwin'
    - 'linux'
  cpu:
    - 'x64'
    - 'x86'
    - 'arm'
  libc:
    - 'glibc'
    - 'musl'
