export const animator: string;
export const groupName: string;
export const resultItem: string;
export const resultItemActive: string;
export const resultItemIcon: string;
export const resultItemIconSubtitle: string;
export const resultItemShortCut: string;
export const search: string;
export const text: string;
