name: code check

on: [pull_request]

jobs:
  merge-gatekeeper:
    name: Mergeability
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          self: Mergeability

  pnpm-check:
    name: Pnpm ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: ["lint:ci", "format:ci", "styles"]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: 'pnpm'

      - name: Install project dependencies
        run: pnpm install

      - name: Check ${{ matrix.command }}
        run: pnpm --silent ${{ matrix.command }}
        env:
          FORCE_COLOR: 2
